title: Vahatra Harilalanjatovo # your name (or website title) here
logo: "/images/me_2.png?raw=true" # your photo (or logo) here
description:
  > # your text below (remove <br> elements if you don't need line breaks)
  A software engineer with experience in Ethereum based blockchain, Web/DApp development with Django/React and Cloud development on AWS platform.
  <br><br>
  <a href="https://github.com/Vahatra" target="_blank">GitHub</a> - <a href="https://www.linkedin.com/in/vahatra-harilalanjatovo/" target="_blank">LinkedIn</a> 
  <br><br>
  Resume <a href="resume-en.pdf" target="_blank">EN</a> - <a href="resume-fr.pdf" target="_blank">FR</a> 
  <br><br>
  Email: h.vahatra.d@gmail.com
show_downloads: false
theme: jekyll-theme-minimal
